# Generated by Django 5.0.3 on 2024-04-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authenticatedmessage',
            options={'permissions': [('send_authenticatedmessage', 'Can send msgs'), ('receive_authenticatedmessage', 'Can receive msgs')]},
        ),
    ]
